### ISSUE TITLE
Assignment 4 generates empty output

### ISSUE THREAD

**Issue by weiguanghuang** [cmaron/CS-7641-assignments#21]
after running $python run_experiment.py --plot
only output/report directory has params.csv, 
other subdirectories - output/images, output/PI, output/Q, output/VI are empty...

**Comment by kuthalam** [comment]
Same here. I am running "python run_experiment.py --plot" with Python 3.7.2 on Windows 10.

**Comment by rushx1** [comment]
There are other '--' options you can specify for command line. You may look more closely at run_experiment.py

**Comment by kuthalam** [comment]
Yes, after some digging, I found that the '--all' flag needed to be run first.

**Comment by weiguanghuang** [comment]
Thanks. My bad.
