### ISSUE TITLE
tsp.py and other algorithms exits with No Attribute Error (Maybe it is ABAGAIL)

### ISSUE THREAD

**Issue by obdrpi** [cmaron/CS-7641-assignments#7]
This is the screenshot:

Traceback (most recent call last):
  File "tsp.py", line 72, in <module>
    fevals = ef.fevals
AttributeError: 'opt.example.TravelingSalesmanRouteEvaluationFuncti' object has no attribute 'fevals'

**Comment by cmaron** [comment]
If you are using a different ABAGAIL.jar this can happen... The source in this repo and the included jar should be based on jontay's code which adds the fevals data.

**Comment by obdrpi** [comment]
Thanks! With the ABAGAIL already included in the repo, it worked fine. Just wondering why would it happen though..

**Comment by cmaron** [comment]
So when jontay worked on this his semester he added that attribute to track the number of times a function was called. If you use the stock ABAGAIL source and jar it won't be there. Not sure what happened in your case, however.

**Comment by obdrpi** [comment]
Yeah, that's good. But then, we have to be cautious to mention that in the README so that TA does not use the stock ABAGAIL jar. Closing this issue.
